// Every app command must be listed here; tauri-build generates an
// `allow-<command>` permission for each, and only commands granted in
// `capabilities/` are callable from the webview.
const COMMANDS: &[&str] = &[
    "get_bootstrap",
    "save_settings",
    "open_data_dir",
    "list_versions",
    "list_java",
    "save_text_file",
    "list_instances",
    "create_instance",
    "update_instance",
    "delete_instance",
    "copy_instance",
    "reorder_instances",
    "select_instance",
    "export_instance",
    "import_instance",
    "open_instance_folder",
    "launch_instance",
    "repair_instance",
    "stop_instance",
    "list_tasks",
    "cancel_task",
    "clear_tasks",
    "list_accounts",
    "add_offline_account",
    "remove_account",
    "rename_account",
    "select_account",
    "list_instance_files",
    "instance_folder_path",
    "toggle_instance_file",
    "delete_instance_file",
    "read_instance_log",
    "list_loader_versions",
    "import_optifine",
    "install_shader_support",
    "search_modrinth",
    "project_versions",
    "install_content",
    "scan_content",
    "update_content",
    "import_modpack",
    "install_modrinth_modpack",
    "content_icon",
    "open_external",
    "list_skins",
    "import_skin_file",
    "add_skin_bytes",
    "list_default_skins",
    "update_skin",
    "delete_skin",
    "assign_skin",
    "export_skin",
    "list_news",
    "analyze_crash_report",
    "open_data_file",
    "move_data_folder",
    "default_data_folder",
    "restart_app",
    "check_app_update",
    "install_app_update",
    "pick_path",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
