//! Instances: isolated game directories under `instances/<id>/` with an
//! `instance.json` describing version, loader and per-instance settings.

pub mod files;
pub mod transfer;

use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::error::{CoreError, Result};
use crate::fsutil::write_json_atomic;
use crate::paths::Paths;
use crate::state::LauncherState;

pub const INSTANCE_FILE: &str = "instance.json";
pub const SCHEMA_VERSION: u32 = 1;
/// Folders every instance gets on creation.
pub const SUBDIRS: &[&str] = &[
    "mods",
    "config",
    "saves",
    "resourcepacks",
    "shaderpacks",
    "screenshots",
    "logs",
];
const MAX_NAME_LEN: usize = 64;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub enum LoaderKind {
    #[default]
    Vanilla,
    Fabric,
    Quilt,
    LegacyFabric,
    Forge,
    NeoForge,
    Optifine,
}

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct LoaderSpec {
    pub kind: LoaderKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[ts(optional)]
    pub version: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[ts(export)]
pub struct Resolution {
    pub width: u32,
    pub height: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct Instance {
    #[serde(default)]
    pub schema_version: u32,
    /// Folder name; authoritative value is the directory, not the file.
    #[serde(default)]
    pub id: String,
    pub name: String,
    /// Preset icon key rendered by the UI (`grass`, `pickaxe`, …).
    #[serde(default = "default_icon")]
    pub icon: String,
    pub mc_version: String,
    #[serde(default)]
    pub loader: LoaderSpec,
    /// Explicit `java` executable; `None` = automatic.
    #[serde(default)]
    pub java_path: Option<String>,
    /// `None` = launcher default.
    #[serde(default)]
    pub memory_mb: Option<u32>,
    /// Extra JVM arguments, space separated (quotes supported).
    #[serde(default)]
    pub jvm_args: String,
    #[serde(default)]
    pub resolution: Option<Resolution>,
    #[serde(default)]
    pub fullscreen: bool,
    #[serde(default)]
    #[ts(type = "number")]
    pub created_at: u64,
    #[serde(default)]
    #[ts(type = "number | null")]
    pub last_played: Option<u64>,
    #[serde(default)]
    #[ts(type = "number")]
    pub play_time_secs: u64,
}

fn default_icon() -> String {
    "grass".into()
}

/// Creation request from the wizard.
#[derive(Debug, Clone, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(export)]
pub struct NewInstance {
    pub name: String,
    #[ts(optional)]
    pub icon: Option<String>,
    pub mc_version: String,
    #[ts(optional)]
    pub loader: Option<LoaderSpec>,
    #[ts(optional)]
    pub java_path: Option<String>,
    #[ts(optional)]
    pub memory_mb: Option<u32>,
    #[ts(optional)]
    pub jvm_args: Option<String>,
    #[ts(optional)]
    pub resolution: Option<Resolution>,
    #[ts(optional)]
    pub fullscreen: Option<bool>,
}

/// Partial update from the settings tab. `Some(None)`-style clears are
/// expressed with dedicated `clear_*` flags to keep the JSON simple.
#[derive(Debug, Clone, Default, Deserialize, TS)]
#[serde(rename_all = "camelCase", default)]
#[ts(export)]
pub struct InstancePatch {
    #[ts(optional)]
    pub name: Option<String>,
    #[ts(optional)]
    pub icon: Option<String>,
    #[ts(optional)]
    pub java_path: Option<String>,
    #[ts(optional)]
    pub clear_java_path: Option<bool>,
    #[ts(optional)]
    pub memory_mb: Option<u32>,
    #[ts(optional)]
    pub clear_memory: Option<bool>,
    #[ts(optional)]
    pub jvm_args: Option<String>,
    #[ts(optional)]
    pub resolution: Option<Resolution>,
    #[ts(optional)]
    pub clear_resolution: Option<bool>,
    #[ts(optional)]
    pub fullscreen: Option<bool>,
}

pub fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or_default()
}

/// Instance ids are generated by us and must stay path-safe.
pub fn validate_id(id: &str) -> Result<()> {
    let ok = !id.is_empty()
        && id.len() <= 64
        && !id.starts_with('.')
        && id.chars().all(|c| {
            c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-' || c == '_' || c == '.'
        });
    if ok && !id.contains("..") {
        Ok(())
    } else {
        Err(CoreError::InstanceNotFound(id.to_owned()))
    }
}

fn validate_name(name: &str) -> Result<String> {
    let n = name.trim();
    if n.is_empty() || n.chars().count() > MAX_NAME_LEN {
        return Err(CoreError::InvalidInstance("name".into()));
    }
    Ok(n.to_owned())
}

fn validate_memory(mb: Option<u32>) -> Result<Option<u32>> {
    match mb {
        Some(m) if !crate::settings::MEMORY_MB_RANGE.contains(&m) => {
            Err(CoreError::InvalidInstance("memoryMb".into()))
        }
        other => Ok(other),
    }
}

fn slug(name: &str) -> String {
    let mut s = String::new();
    for c in name.chars() {
        let c = match c {
            'ç' | 'Ç' => 'c',
            'ğ' | 'Ğ' => 'g',
            'ı' | 'İ' => 'i',
            'ö' | 'Ö' => 'o',
            'ş' | 'Ş' => 's',
            'ü' | 'Ü' => 'u',
            c => c.to_ascii_lowercase(),
        };
        if c.is_ascii_alphanumeric() {
            s.push(c);
        } else if !s.ends_with('-') && !s.is_empty() {
            s.push('-');
        }
        if s.len() >= 24 {
            break;
        }
    }
    let s = s.trim_end_matches('-').to_owned();
    if s.is_empty() { "instance".into() } else { s }
}

/// Splits a JVM argument string on whitespace, honouring double quotes.
pub fn split_args(s: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut quoted = false;
    let mut has = false;
    for c in s.chars() {
        match c {
            '"' => {
                quoted = !quoted;
                has = true;
            }
            c if c.is_whitespace() && !quoted => {
                if has {
                    out.push(std::mem::take(&mut cur));
                    has = false;
                }
            }
            c => {
                cur.push(c);
                has = true;
            }
        }
    }
    if has {
        out.push(cur);
    }
    out
}

pub struct InstanceStore {
    paths: Paths,
    write: Mutex<()>,
}

impl InstanceStore {
    pub fn new(paths: Paths) -> Self {
        Self {
            paths,
            write: Mutex::new(()),
        }
    }

    pub fn paths(&self) -> &Paths {
        &self.paths
    }

    pub fn dir(&self, id: &str) -> Result<PathBuf> {
        validate_id(id)?;
        Ok(self.paths.instances().join(id))
    }

    /// All instances in the user's order (unknown ones last, newest first).
    pub fn list(&self) -> Vec<Instance> {
        let Ok(rd) = std::fs::read_dir(self.paths.instances()) else {
            return vec![];
        };
        let mut all: Vec<Instance> = rd
            .flatten()
            .filter(|e| e.path().join(INSTANCE_FILE).is_file())
            .filter_map(|e| {
                let id = e.file_name().to_string_lossy().into_owned();
                validate_id(&id).ok()?;
                match self.read(&id) {
                    Ok(i) => Some(i),
                    Err(err) => {
                        tracing::warn!(%id, error = %err.detail(), "skipping unreadable instance");
                        None
                    }
                }
            })
            .collect();
        let order = LauncherState::load(&self.paths).instance_order;
        all.sort_by(|a, b| {
            let pa = order.iter().position(|x| *x == a.id);
            let pb = order.iter().position(|x| *x == b.id);
            match (pa, pb) {
                (Some(x), Some(y)) => x.cmp(&y),
                (Some(_), None) => std::cmp::Ordering::Less,
                (None, Some(_)) => std::cmp::Ordering::Greater,
                (None, None) => b.created_at.cmp(&a.created_at),
            }
        });
        all
    }

    pub fn get(&self, id: &str) -> Result<Instance> {
        validate_id(id)?;
        if !self
            .paths
            .instances()
            .join(id)
            .join(INSTANCE_FILE)
            .is_file()
        {
            return Err(CoreError::InstanceNotFound(id.to_owned()));
        }
        self.read(id)
    }

    fn read(&self, id: &str) -> Result<Instance> {
        let path = self.paths.instances().join(id).join(INSTANCE_FILE);
        let bytes = std::fs::read(&path).map_err(|e| CoreError::io(&path, e))?;
        let mut inst: Instance =
            serde_json::from_slice(&bytes).map_err(|source| CoreError::Json { path, source })?;
        inst.id = id.to_owned();
        Ok(inst)
    }

    pub fn save(&self, inst: &Instance) -> Result<()> {
        let dir = self.dir(&inst.id)?;
        write_json_atomic(&dir.join(INSTANCE_FILE), inst)
    }

    fn unique_id(&self, name: &str) -> String {
        let base = slug(name);
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.subsec_nanos())
            .unwrap_or_default();
        let mut n = nanos;
        loop {
            let id = format!("{base}-{:06x}", n & 0xff_ffff);
            if !self.paths.instances().join(&id).exists() {
                return id;
            }
            n = n.wrapping_add(7919);
        }
    }

    pub fn create(&self, req: NewInstance) -> Result<Instance> {
        let _w = self.write.lock().expect("instance lock");
        let name = validate_name(&req.name)?;
        if req.mc_version.trim().is_empty() {
            return Err(CoreError::InvalidInstance("mcVersion".into()));
        }
        let id = self.unique_id(&name);
        let dir = self.paths.instances().join(&id);
        for sub in SUBDIRS {
            let d = dir.join(sub);
            std::fs::create_dir_all(&d).map_err(|e| CoreError::io(&d, e))?;
        }
        let inst = Instance {
            schema_version: SCHEMA_VERSION,
            id: id.clone(),
            name,
            icon: req.icon.unwrap_or_else(default_icon),
            mc_version: req.mc_version.trim().to_owned(),
            loader: req.loader.unwrap_or_default(),
            java_path: req.java_path.filter(|p| !p.trim().is_empty()),
            memory_mb: validate_memory(req.memory_mb)?,
            jvm_args: req.jvm_args.unwrap_or_default(),
            resolution: req.resolution,
            fullscreen: req.fullscreen.unwrap_or(false),
            created_at: now_secs(),
            last_played: None,
            play_time_secs: 0,
        };
        self.save(&inst)?;
        LauncherState::update(&self.paths, |s| {
            s.instance_order.insert(0, id.clone());
            s.selected_instance.get_or_insert(id.clone());
        })?;
        tracing::info!(%id, version = %inst.mc_version, "instance created");
        Ok(inst)
    }

    pub fn update(&self, id: &str, patch: InstancePatch) -> Result<Instance> {
        let _w = self.write.lock().expect("instance lock");
        let mut inst = self.get(id)?;
        if let Some(n) = patch.name {
            inst.name = validate_name(&n)?;
        }
        if let Some(i) = patch.icon {
            inst.icon = i;
        }
        if patch.clear_java_path == Some(true) {
            inst.java_path = None;
        } else if let Some(p) = patch.java_path.filter(|p| !p.trim().is_empty()) {
            inst.java_path = Some(p);
        }
        if patch.clear_memory == Some(true) {
            inst.memory_mb = None;
        } else if let Some(m) = patch.memory_mb {
            inst.memory_mb = validate_memory(Some(m))?;
        }
        if let Some(a) = patch.jvm_args {
            inst.jvm_args = a;
        }
        if patch.clear_resolution == Some(true) {
            inst.resolution = None;
        } else if let Some(r) = patch.resolution {
            inst.resolution = Some(r);
        }
        if let Some(f) = patch.fullscreen {
            inst.fullscreen = f;
        }
        self.save(&inst)?;
        Ok(inst)
    }

    pub fn delete(&self, id: &str) -> Result<()> {
        let _w = self.write.lock().expect("instance lock");
        let dir = self.dir(id)?;
        if !dir.join(INSTANCE_FILE).is_file() {
            return Err(CoreError::InstanceNotFound(id.to_owned()));
        }
        std::fs::remove_dir_all(&dir).map_err(|e| CoreError::io(&dir, e))?;
        LauncherState::update(&self.paths, |s| {
            s.instance_order.retain(|x| x != id);
            if s.selected_instance.as_deref() == Some(id) {
                s.selected_instance = None;
            }
        })?;
        tracing::info!(%id, "instance deleted");
        Ok(())
    }

    /// Duplicates an instance (worlds, mods, config…) except logs and crash reports.
    pub fn copy(&self, id: &str, new_name: &str) -> Result<Instance> {
        let src = self.get(id)?;
        let name = validate_name(new_name)?;
        let _w = self.write.lock().expect("instance lock");
        let new_id = self.unique_id(&name);
        let from = self.paths.instances().join(id);
        let to = self.paths.instances().join(&new_id);
        crate::fsutil::copy_dir(&from, &to, &|rel: &Path| {
            let first = rel
                .components()
                .next()
                .map(|c| c.as_os_str().to_string_lossy().into_owned());
            matches!(
                first.as_deref(),
                Some("logs" | "crash-reports" | ".mehbur.lock")
            )
        })?;
        std::fs::create_dir_all(to.join("logs")).map_err(|e| CoreError::io(&to, e))?;
        let inst = Instance {
            id: new_id.clone(),
            name,
            created_at: now_secs(),
            last_played: None,
            play_time_secs: 0,
            ..src
        };
        self.save(&inst)?;
        LauncherState::update(&self.paths, |s| {
            let pos = s
                .instance_order
                .iter()
                .position(|x| x == id)
                .map_or(0, |p| p + 1);
            s.instance_order
                .insert(pos.min(s.instance_order.len()), new_id.clone());
        })?;
        Ok(inst)
    }

    /// Adds a finished play session to the statistics.
    pub fn record_session(&self, id: &str, secs: u64) -> Result<Instance> {
        let _w = self.write.lock().expect("instance lock");
        let mut inst = self.get(id)?;
        inst.play_time_secs += secs;
        inst.last_played = Some(now_secs());
        self.save(&inst)?;
        Ok(inst)
    }

    pub fn reorder(&self, ids: Vec<String>) -> Result<()> {
        for id in &ids {
            validate_id(id)?;
        }
        LauncherState::update(&self.paths, |s| s.instance_order = ids)
    }
}

/// Instances that are currently being prepared or played.
#[derive(Clone, Default)]
pub struct Running(Arc<Mutex<HashSet<String>>>);

/// Released on drop.
pub struct Claim {
    set: Arc<Mutex<HashSet<String>>>,
    id: String,
}

impl Drop for Claim {
    fn drop(&mut self) {
        self.set.lock().expect("running lock").remove(&self.id);
    }
}

impl Running {
    pub fn try_claim(&self, inst: &Instance) -> Result<Claim> {
        let mut set = self.0.lock().expect("running lock");
        if !set.insert(inst.id.clone()) {
            return Err(CoreError::InstanceBusy {
                name: inst.name.clone(),
            });
        }
        Ok(Claim {
            set: self.0.clone(),
            id: inst.id.clone(),
        })
    }

    pub fn is_running(&self, id: &str) -> bool {
        self.0.lock().expect("running lock").contains(id)
    }

    pub fn ensure_idle(&self, inst: &Instance) -> Result<()> {
        if self.is_running(&inst.id) {
            Err(CoreError::InstanceBusy {
                name: inst.name.clone(),
            })
        } else {
            Ok(())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    pub(crate) fn store() -> (tempfile::TempDir, InstanceStore) {
        let tmp = tempfile::tempdir().unwrap();
        let paths = Paths::at(tmp.path().join("MehburMC"));
        paths.ensure_layout().unwrap();
        (tmp, InstanceStore::new(paths))
    }

    pub(crate) fn new(name: &str) -> NewInstance {
        NewInstance {
            name: name.into(),
            icon: None,
            mc_version: "26.3".into(),
            loader: None,
            java_path: None,
            memory_mb: None,
            jvm_args: None,
            resolution: None,
            fullscreen: None,
        }
    }

    #[test]
    fn create_list_update_delete() {
        let (_t, s) = store();
        let a = s.create(new("Survival Dünyası")).unwrap();
        assert!(a.id.starts_with("survival-dunyasi-"), "{}", a.id);
        for sub in SUBDIRS {
            assert!(s.dir(&a.id).unwrap().join(sub).is_dir(), "{sub}");
        }
        let b = s.create(new("Creative")).unwrap();
        // Newest first in the order list.
        let ids: Vec<_> = s.list().into_iter().map(|i| i.id).collect();
        assert_eq!(ids, [b.id.clone(), a.id.clone()]);

        let u = s
            .update(
                &a.id,
                InstancePatch {
                    name: Some("  Yeni Ad ".into()),
                    memory_mb: Some(6144),
                    ..Default::default()
                },
            )
            .unwrap();
        assert_eq!(u.name, "Yeni Ad");
        assert_eq!(u.memory_mb, Some(6144));
        assert!(
            s.update(
                &a.id,
                InstancePatch {
                    memory_mb: Some(1),
                    ..Default::default()
                }
            )
            .is_err()
        );

        s.reorder(vec![a.id.clone(), b.id.clone()]).unwrap();
        assert_eq!(s.list()[0].id, a.id);

        s.delete(&a.id).unwrap();
        assert_eq!(s.list().len(), 1);
        assert_eq!(s.get(&a.id).unwrap_err().code(), "instance.notFound");
    }

    #[test]
    fn copy_skips_logs_and_resets_stats() {
        let (_t, s) = store();
        let a = s.create(new("Base")).unwrap();
        let dir = s.dir(&a.id).unwrap();
        std::fs::write(dir.join("mods").join("m.jar"), b"jar").unwrap();
        std::fs::write(dir.join("logs").join("latest.log"), b"log").unwrap();
        s.record_session(&a.id, 120).unwrap();

        let c = s.copy(&a.id, "Base (kopya)").unwrap();
        let cdir = s.dir(&c.id).unwrap();
        assert!(cdir.join("mods").join("m.jar").is_file());
        assert!(!cdir.join("logs").join("latest.log").exists());
        assert_eq!(c.play_time_secs, 0);
        assert_eq!(s.get(&a.id).unwrap().play_time_secs, 120);
    }

    #[test]
    fn ids_are_path_safe() {
        let (_t, s) = store();
        for bad in ["../x", "a/b", "a\\b", "", ".hidden", "UPPER", "a..b"] {
            assert!(s.dir(bad).is_err(), "{bad}");
        }
        assert_eq!(slug("!!!"), "instance");
        assert_eq!(slug("İstanbul Şehri"), "istanbul-sehri");
    }

    #[test]
    fn running_claims() {
        let (_t, s) = store();
        let a = s.create(new("A")).unwrap();
        let r = Running::default();
        let claim = r.try_claim(&a).unwrap();
        assert_eq!(r.try_claim(&a).err().unwrap().code(), "instance.busy");
        drop(claim);
        assert!(r.try_claim(&a).is_ok());
    }

    #[test]
    fn arg_splitting() {
        assert_eq!(
            split_args(r#"-XX:+UseG1GC  -Dfoo="a b" -Xss2M"#),
            ["-XX:+UseG1GC", "-Dfoo=a b", "-Xss2M"]
        );
        assert!(split_args("   ").is_empty());
    }
}
