//! Library resolution: rules, Maven paths, legacy `natives` maps and modern
//! `natives-*` classifier libraries, classpath de-duplication.

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use crate::hash::Checksum;
use crate::maven::Coordinate;
use crate::net::download::DownloadItem;
use crate::rules::{RuleEnv, allowed};
use crate::version::profile::{Artifact, Library};

const MOJANG_LIBRARIES: &str = "https://libraries.minecraft.net/";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LibArtifact {
    pub name: String,
    pub path: PathBuf,
    /// `None` for files that must already exist (generated by an installer).
    pub url: Option<String>,
    pub sha1: Option<String>,
    pub size: Option<u64>,
}

impl LibArtifact {
    pub fn download_item(&self) -> Option<DownloadItem> {
        self.url.as_ref().map(|url| DownloadItem {
            url: url.clone(),
            dest: self.path.clone(),
            checksum: self.sha1.clone().map(Checksum::Sha1),
            size: self.size,
        })
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NativeJar {
    pub artifact: LibArtifact,
    /// Path prefixes not to extract (`extract.exclude`).
    pub exclude: Vec<String>,
    /// Modern LWJGL 3 natives jars nest files in `windows/x64/...`; those are
    /// flattened so they sit directly on `java.library.path`.
    pub flatten: bool,
}

#[derive(Debug, Clone, Default)]
pub struct ResolvedLibraries {
    pub classpath: Vec<LibArtifact>,
    pub natives: Vec<NativeJar>,
}

impl ResolvedLibraries {
    pub fn download_items(&self) -> Vec<DownloadItem> {
        let mut seen = HashSet::new();
        self.classpath
            .iter()
            .chain(self.natives.iter().map(|n| &n.artifact))
            .filter(|a| seen.insert(a.path.clone()))
            .filter_map(LibArtifact::download_item)
            .collect()
    }
}

pub fn resolve(libs: &[Library], env: &RuleEnv, libraries_dir: &Path) -> ResolvedLibraries {
    let mut out = ResolvedLibraries::default();
    let mut seen = HashSet::new();

    for lib in libs {
        if !allowed(&lib.rules, env) {
            continue;
        }
        let Some(coord) = Coordinate::parse(&lib.name) else {
            tracing::warn!(name = %lib.name, "skipping library with invalid coordinate");
            continue;
        };
        let downloads = lib.downloads.as_ref();

        // Legacy natives map: { "windows": "natives-windows-${arch}" }.
        if let Some(natives) = &lib.natives {
            if let Some(classifier) = natives.get(env.os.name) {
                let classifier = classifier.replace("${arch}", env.os.bitness());
                let declared = downloads
                    .and_then(|d| d.classifiers.as_ref())
                    .and_then(|c| c.get(&classifier));
                let artifact = artifact_for(
                    &coord.with_classifier(&classifier),
                    declared,
                    lib,
                    libraries_dir,
                );
                out.natives.push(NativeJar {
                    artifact,
                    exclude: lib
                        .extract
                        .as_ref()
                        .map(|e| e.exclude.clone())
                        .unwrap_or_default(),
                    flatten: false,
                });
            }
            // A natives library may also ship a (tiny) main artifact.
            if let Some(main) = downloads.and_then(|d| d.artifact.as_ref())
                && seen.insert(coord.dedup_key())
            {
                out.classpath
                    .push(artifact_for(&coord, Some(main), lib, libraries_dir));
            }
            continue;
        }

        if !seen.insert(coord.dedup_key()) {
            continue; // an earlier (child/loader) entry already won
        }
        let artifact = artifact_for(
            &coord,
            downloads.and_then(|d| d.artifact.as_ref()),
            lib,
            libraries_dir,
        );

        // Modern natives are regular classpath entries; extract the ones for
        // this machine's arch too so java.library.path has them.
        if let Some(classifier) = &coord.classifier
            && classifier.starts_with("natives-")
            && env.os.matches_native_classifier(classifier)
        {
            out.natives.push(NativeJar {
                artifact: artifact.clone(),
                exclude: vec!["META-INF/".into()],
                flatten: true,
            });
        }
        out.classpath.push(artifact);
    }
    out
}

fn artifact_for(
    coord: &Coordinate,
    declared: Option<&Artifact>,
    lib: &Library,
    libraries_dir: &Path,
) -> LibArtifact {
    let rel = declared
        .and_then(|a| a.path.clone())
        .unwrap_or_else(|| coord.path());
    let url = match declared {
        Some(a) if a.url.is_empty() => None,
        Some(a) => Some(a.url.clone()),
        None => {
            let base = lib.url.as_deref().unwrap_or(MOJANG_LIBRARIES);
            let sep = if base.ends_with('/') { "" } else { "/" };
            Some(format!("{base}{sep}{rel}"))
        }
    };
    LibArtifact {
        name: coord.to_string(),
        path: rel
            .split('/')
            .fold(libraries_dir.to_path_buf(), |p, seg| p.join(seg)),
        url,
        sha1: declared.and_then(|a| a.sha1.clone()).or(lib.sha1.clone()),
        size: declared.and_then(|a| a.size).or(lib.size),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::os::OsInfo;
    use crate::version::profile::VersionJson;

    fn fixture(name: &str) -> VersionJson {
        let p = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("tests/fixtures/versions")
            .join(name);
        serde_json::from_slice(&std::fs::read(p).unwrap()).unwrap()
    }

    fn win64() -> RuleEnv {
        RuleEnv::new(OsInfo::fake("windows", "x86_64"))
    }

    #[test]
    fn modern_natives_26_3() {
        let v = fixture("26.3.json");
        let r = resolve(&v.libraries, &win64(), Path::new("L"));
        // No linux/osx libraries on the classpath.
        assert!(
            r.classpath
                .iter()
                .all(|a| !a.name.contains("natives-linux"))
        );
        assert!(
            r.classpath
                .iter()
                .all(|a| !a.name.contains("java-objc-bridge"))
        );
        // Both windows classifiers are on the classpath (Mojang behaviour) …
        assert!(
            r.classpath
                .iter()
                .any(|a| a.name == "org.lwjgl:lwjgl:3.4.3:natives-windows")
        );
        assert!(
            r.classpath
                .iter()
                .any(|a| a.name == "org.lwjgl:lwjgl:3.4.3:natives-windows-arm64")
        );
        // … but only the x64 one is extracted.
        assert!(
            r.natives
                .iter()
                .all(|n| !n.artifact.name.ends_with("arm64"))
        );
        assert!(
            r.natives
                .iter()
                .any(|n| n.artifact.name == "org.lwjgl:lwjgl:3.4.3:natives-windows")
        );
        assert!(r.natives.iter().all(|n| n.flatten));
        // Every Mojang artifact carries a URL + sha1 + size.
        assert!(
            r.classpath
                .iter()
                .all(|a| a.url.is_some() && a.sha1.is_some() && a.size.is_some())
        );
        // No duplicates.
        let mut paths: Vec<_> = r.classpath.iter().map(|a| &a.path).collect();
        let n = paths.len();
        paths.dedup();
        assert_eq!(paths.len(), n);
    }

    #[test]
    fn legacy_natives_1_12_2() {
        let v = fixture("1.12.2.json");
        let r = resolve(&v.libraries, &win64(), Path::new("L"));
        let names: Vec<_> = r.natives.iter().map(|n| n.artifact.name.as_str()).collect();
        assert!(
            names
                .contains(&"org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209:natives-windows")
        );
        assert!(names.contains(&"net.java.jinput:jinput-platform:2.0.5:natives-windows"));
        // 2.9.2 is osx-only and must not appear on windows.
        assert!(!names.iter().any(|n| n.contains("2.9.2-nightly")));
        assert!(
            r.natives
                .iter()
                .all(|n| n.exclude == ["META-INF/"] && !n.flatten)
        );
        assert!(!r.classpath.iter().any(|a| a.name.contains("2.9.2-nightly")));
    }

    #[test]
    fn maven_only_loader_library_and_dedup() {
        let libs: Vec<Library> = serde_json::from_str(
            r#"[{"name":"org.ow2.asm:asm:9.10.1","url":"https://maven.fabricmc.net/","sha1":"ada2","size":126151},
                {"name":"org.ow2.asm:asm:9.6","downloads":{"artifact":{"path":"org/ow2/asm/asm/9.6/asm-9.6.jar","url":"https://libraries.minecraft.net/org/ow2/asm/asm/9.6/asm-9.6.jar","sha1":"x","size":1}}},
                {"name":"net.minecraftforge:forge:47.1.0:client","downloads":{"artifact":{"path":"net/minecraftforge/forge/47.1.0/forge-47.1.0-client.jar","url":""}}}]"#,
        )
        .unwrap();
        let r = resolve(&libs, &win64(), Path::new("L"));
        assert_eq!(r.classpath.len(), 2);
        assert_eq!(
            r.classpath[0].url.as_deref(),
            Some("https://maven.fabricmc.net/org/ow2/asm/asm/9.10.1/asm-9.10.1.jar")
        );
        assert_eq!(r.classpath[0].sha1.as_deref(), Some("ada2"));
        assert!(
            r.classpath[1].url.is_none(),
            "installer-generated file has no URL"
        );
        assert_eq!(r.download_items().len(), 1);
    }
}
