// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Faces of the launcher accounts for the UI (`account id → data: URI`).
 */
export type AccountFaces = { 
/**
 * Chosen profile photos.
 */
photos: { [key in string]: string }, 
/**
 * Game default skin of accounts that have no skin assigned.
 */
defaultSkins: { [key in string]: string }, 
/**
 * Accounts whose name another user holds (rename them).
 */
nameConflicts: Array<string>, };
