// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountKind } from "./AccountKind";

export type Account = { id: string, kind: AccountKind, name: string, 
/**
 * Hyphenated UUID.
 */
uuid: string, addedAt: number, };
