// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminUser = { userId: string, names: Array<string>, rank: number, banned: boolean, banUntil: string | null, };
