// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryMod } from "./LibraryMod";

export type AdminMod = { mod: LibraryMod, 
/**
 * Uploader's user id.
 */
owner: string, reports: number, };
