// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminBan = { userId: string, names: Array<string>, 
/**
 * `None` = permanent.
 */
until: string | null, reason: string, bannedBy: Array<string>, createdAt: string, active: boolean, };
