// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkinModel } from "./SkinModel";
import type { TextureKind } from "./TextureKind";
import type { Visibility } from "./Visibility";

/**
 * A share as the founder sees it in the Admin panel (K74).
 */
export type AdminTexture = { id: number, kind: TextureKind, model: SkinModel, name: string, author: string, 
/**
 * User id of the person who shared it (for bans).
 */
owner: string, visibility: Visibility, 
/**
 * RFC 3339.
 */
createdAt: string, 
/**
 * Removed from the community.
 */
hidden: boolean, 
/**
 * None when the image is missing or fails verification.
 */
dataUri: string | null, };
