// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportKind } from "./ReportKind";

export type AdminReport = { kind: ReportKind, itemId: number, name: string, author: string, owner: string, sha1: string, reports: number, reasons: Array<string>, notes: Array<string>, lastReport: string, };
