// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateStatus } from "./UpdateStatus";

export type AppUpdate = { status: UpdateStatus, current: string, version: string | null, notes: string | null, };
