// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthSettings = { 
/**
 * Azure application (client) id for Microsoft login. Never shipped in
 * the binary; `MEHBURMC_MSA_CLIENT_ID` overrides it.
 */
msaClientId?: string, };
