// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BanInfo } from "./BanInfo";

export type AuthStatus = { 
/**
 * Signed in with an email account (the launcher is usable).
 */
signedIn: boolean, email: string | null, 
/**
 * An anonymous identity of an older launcher exists: signing up
 * upgrades it and keeps its friends, names and shares.
 */
anonymousIdentity: boolean, 
/**
 * Admin rank: 0 none, 1 founder, 2 admin.
 */
rank: number, ban: BanInfo | null, 
/**
 * The server could not be reached; rank/ban are the last known ones.
 */
offline: boolean, };
