// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BanInfo = { 
/**
 * RFC 3339; `None` = permanent (or unknown when sign-in was refused).
 */
until: string | null, reason: string, };
