// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file the pack needs but that could not be downloaded automatically.
 */
export type BlockedFile = { name: string, 
/**
 * Page where the user can download it manually.
 */
url: string, 
/**
 * Folder it belongs in (`mods`, `resourcepacks`, …).
 */
folder: string, };
