// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorPayload } from "./ErrorPayload";
import type { PathsInfo } from "./PathsInfo";
import type { Settings } from "./Settings";

/**
 * Everything the UI needs for its first render, in one round trip.
 */
export type Bootstrap = { appName: string, version: string, paths: PathsInfo | null, settings: Settings, startupError: ErrorPayload | null, 
/**
 * Set on the first start after an update (see `note_launcher_version`).
 */
updatedFrom: string | null, };
