// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CapeItem = { dataUri: string, 
/**
 * SHA-1 of the PNG.
 */
id: string, name: string, addedAt: number, };
