// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatMessage = { id: number, sender: string, recipient: string, body: string, createdAt: string, readAt: string | null, };
