// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogStream } from "./LogStream";
import type { Stage } from "./Stage";

export type CoreEvent = { "type": "progress", task: string, stage: Stage, done: number, total: number, bytesDone: number, bytesTotal: number, } | { "type": "gameLog", task: string, stream: LogStream, line: string, } | { "type": "gameExited", task: string, code: number | null, crashReport: string | null, };
