// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";
import type { LogStream } from "./LogStream";
import type { Stage } from "./Stage";
import type { TaskInfo } from "./TaskInfo";

export type CoreEvent = { "type": "task", task: TaskInfo, } | { "type": "progress", task: string, stage: Stage, done: number, total: number, bytesDone: number, bytesTotal: number, } | { "type": "gameLog", task: string, stream: LogStream, line: string, level: LogLevel | null, 
/**
 * Unix milliseconds from the log4j event, if the game provided one.
 */
timeMs: number | null, thread: string | null, } | { "type": "gameExited", task: string, code: number | null, crashReport: string | null, };
