// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnosis } from "./Diagnosis";

export type CrashInfo = { instanceId: string, instanceName: string, exitCode: number | null, 
/**
 * Most specific first.
 */
diagnoses: Array<Diagnosis>, 
/**
 * Crash report "Description" or the first exception line.
 */
summary: string | null, crashReport: string | null, hsErr: string | null, logFile: string | null, };
