// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkinModel } from "./SkinModel";

export type DefaultSkin = { 
/**
 * Capitalised file stem, e.g. "Steve".
 */
name: string, model: SkinModel, dataUri: string, 
/**
 * Version id of the jar the skins were read from.
 */
source: string, };
