// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable error shape returned over IPC.
 */
export type ErrorPayload = { code: string, params: { [key in string]: string }, detail: string, };
