// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FavoriteServer = { 
/**
 * Derived from the normalised address, so each server is listed once.
 */
id: string, name: string, address: string, addedAt: number, };
