// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileEntry = { name: string, size: number, modified: number, isDir: boolean, 
/**
 * `false` for `*.disabled` mods/packs.
 */
enabled: boolean, };
