// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Severity } from "./Severity";

export type Finding = { severity: Severity, 
/**
 * Stable code, translated as `library.findings.<code>`.
 */
code: string, 
/**
 * Where it was seen (class or file names), a few examples.
 */
examples: Array<string>, };
