// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Folder = "root" | "mods" | "resourcePacks" | "shaderPacks" | "saves" | "screenshots" | "logs" | "crashReports";
