// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FriendStatus } from "./FriendStatus";

export type Friend = { id: string, friendCode: string, displayName: string, status: FriendStatus, 
/**
 * For pending requests: sent to me (true) or by me (false).
 */
incoming: boolean, requestId: number, unread: number, };
