// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FriendInstallResult = { installed: Array<string>, 
/**
 * Identical file already in the folder.
 */
alreadyPresent: Array<string>, 
/**
 * A different file with the same name exists; left untouched.
 */
conflicts: Array<string>, 
/**
 * Not downloadable (too large or invalid entry).
 */
skipped: Array<string>, };
