// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Profile } from "./Profile";

export type FriendsStatus = { 
/**
 * The user turned friends on (an identity exists).
 */
enabled: boolean, profile: Profile | null, 
/**
 * Friends see us online (the last heartbeat succeeded).
 */
online: boolean, };
