// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An entry of the game's multiplayer list.
 */
export type GameServer = { 
/**
 * Position in `servers.dat` (needed to remove it).
 */
index: number, name: string, address: string, 
/**
 * Icon the game cached, as a data URI.
 */
icon: string | null, };
