// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockedFile } from "./BlockedFile";
import type { Instance } from "./Instance";

export type ImportResult = { instance: Instance, blocked: Array<BlockedFile>, };
