// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderSpec } from "./LoaderSpec";
import type { Resolution } from "./Resolution";

export type Instance = { schemaVersion: number, 
/**
 * Folder name; authoritative value is the directory, not the file.
 */
id: string, name: string, 
/**
 * Preset icon key rendered by the UI (`grass`, `pickaxe`, …).
 */
icon: string, mcVersion: string, loader: LoaderSpec, 
/**
 * Explicit `java` executable; `None` = automatic.
 */
javaPath: string | null, 
/**
 * `None` = launcher default.
 */
memoryMb: number | null, 
/**
 * Extra JVM arguments, space separated (quotes supported).
 */
jvmArgs: string, resolution: Resolution | null, fullscreen: boolean, createdAt: number, lastPlayed: number | null, playTimeSecs: number, };
