// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateInfo } from "./UpdateInfo";

export type InstalledItem = { fileName: string, enabled: boolean, size: number, 
/**
 * Set when Modrinth knows the file.
 */
projectId: string | null, slug: string | null, title: string | null, versionNumber: string | null, iconUrl: string | null, 
/**
 * A newer compatible version (only when updates were checked).
 */
update: UpdateInfo | null, };
