// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Resolution } from "./Resolution";

/**
 * Partial update from the settings tab. `Some(None)`-style clears are
 * expressed with dedicated `clear_*` flags to keep the JSON simple.
 */
export type InstancePatch = { name?: string, icon?: string, javaPath?: string, clearJavaPath?: boolean, memoryMb?: number, clearMemory?: boolean, jvmArgs?: string, resolution?: Resolution, clearResolution?: boolean, fullscreen?: boolean, };
