// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstallResult = { 
/**
 * Files downloaded.
 */
installed: Array<string>, 
/**
 * Projects skipped because they are already in the folder.
 */
alreadyPresent: Array<string>, 
/**
 * Installed projects that declare an installed mod incompatible.
 */
incompatible: Array<string>, };
