// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectType } from "./ProjectType";

export type InstallRequest = { 
/**
 * Project id or slug.
 */
project: string, projectType: ProjectType, 
/**
 * Exact version; otherwise the newest compatible one.
 */
versionId?: string, };
