// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ItemSource = { "kind": "modrinth", url: string, projectId: string, } | { "kind": "upload", path: string, } | { "kind": "tooLarge" };
