// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JavaInstall = { 
/**
 * The `java` executable.
 */
executable: string, home: string, major: number, version: string, vendor: string | null, arch: string | null, 
/**
 * Downloaded and owned by the launcher.
 */
managed: boolean, };
