// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the launcher window does once the game has started.
 */
export type LaunchBehavior = "minimize" | "close" | "keepOpen";
