// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";

/**
 * Result of an install attempt.
 */
export type LibraryInstall = { "kind": "installed", fileName: string, } | { "kind": "alreadyPresent", fileName: string, } | { "kind": "needsConfirm", findings: Array<Finding>, };
