// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Assignment } from "./Assignment";
import type { CapeItem } from "./CapeItem";
import type { SkinItem } from "./SkinItem";

export type LibraryView = { skins: Array<SkinItem>, capes: Array<CapeItem>, assignments: { [key in string]: Assignment }, };
