// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";
import type { LibraryStatus } from "./LibraryStatus";
import type { ModLoader } from "./ModLoader";

export type LibraryMod = { id: number, 
/**
 * Account name of the uploader.
 */
author: string, name: string, description: string, modId: string, version: string, loaders: Array<ModLoader>, gameVersions: string, sha1: string, size: number, fileName: string, status: LibraryStatus, 
/**
 * The uploader's automatic check (codes filtered to known ones).
 */
findings: Array<Finding>, 
/**
 * Admin's note on a rejection; only for own uploads.
 */
reviewNote: string | null, 
/**
 * RFC 3339.
 */
createdAt: string, 
/**
 * Uploaded by this installation.
 */
mine: boolean, };
