// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderKind } from "./LoaderKind";

export type LoaderSpec = { kind: LoaderKind, version?: string, };
