// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoaderVersion = { 
/**
 * Value stored in `LoaderSpec.version`.
 */
id: string, 
/**
 * Short label for the UI (`47.4.26` for Forge `1.20.1-47.4.26`).
 */
label: string, stable: boolean, 
/**
 * The version picked when the user does not choose one.
 */
recommended: boolean, };
