// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ManifestEntry = { id: string, 
/**
 * `release`, `snapshot`, `old_beta` or `old_alpha`.
 */
type: string, url: string, releaseTime: string, sha1: string | null, };
