// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModLoader } from "./ModLoader";

export type ModDescriptor = { modId: string, name: string, version: string, loaders: Array<ModLoader>, 
/**
 * Minecraft version requirement as written by the mod (may be empty).
 */
gameVersions: string, };
