// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MotdSpan = { text: string, 
/**
 * `#rrggbb`; `None` = default text colour.
 */
color: string | null, bold: boolean, italic: boolean, underlined: boolean, strikethrough: boolean, };
