// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoaderSpec } from "./LoaderSpec";
import type { Resolution } from "./Resolution";

/**
 * Creation request from the wizard.
 */
export type NewInstance = { name: string, icon?: string, mcVersion: string, loader?: LoaderSpec, javaPath?: string, memoryMb?: number, jvmArgs?: string, resolution?: Resolution, fullscreen?: boolean, };
