// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewsItem = { id: string, title: string, text: string, 
/**
 * `YYYY-MM-DD`
 */
date: string, 
/**
 * Absolute image URL (fetch through `content_icon`; CSP blocks it).
 */
image?: string, 
/**
 * minecraft.net article.
 */
link?: string, };
