// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OptifineInfo = { mcVersion: string, 
/**
 * `HD_U_I6`, `HD_U_J1_pre9`, …
 */
edition: string, };
