// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataMode } from "./DataMode";

/**
 * Serializable summary for the UI.
 */
export type PathsInfo = { mode: DataMode, root: string, mc: string, content: string, redirected: boolean, };
