// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PickPurpose = "modpack" | "instanceArchive" | "optifine" | "skin" | "cape" | "avatar" | "java" | "dataFolder" | "instanceExport" | "consoleLog" | "skinExport";
