// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapeEntry } from "./CapeEntry";
import type { SkinEntry } from "./SkinEntry";

export type PlayerImport = { player: string, skin: SkinEntry | null, cape: CapeEntry | null, };
