// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkinModel } from "./SkinModel";
import type { TextureKind } from "./TextureKind";

export type PrivateTexture = { id: number, kind: TextureKind, model: SkinModel, name: string, sha1: string, createdAt: string, grants: number, 
/**
 * `None` if the file could not be fetched.
 */
dataUri: string | null, };
