// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Finding } from "./Finding";
import type { ModDescriptor } from "./ModDescriptor";
import type { Verdict } from "./Verdict";

export type ScanReport = { verdict: Verdict, descriptor: ModDescriptor | null, findings: Array<Finding>, sha1: string, size: number, classes: number, 
/**
 * Version of these rules, so old reports can be told apart.
 */
scanner: number, };
