// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchHit } from "./SearchHit";

export type SearchPage = { hits: Array<SearchHit>, totalHits: number, offset: number, };
