// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectType } from "./ProjectType";
import type { SearchSort } from "./SearchSort";

export type SearchQuery = { query: string, projectType: ProjectType, 
/**
 * Restrict to this Minecraft version.
 */
gameVersion?: string, 
/**
 * Restrict to this Modrinth loader (`fabric`, `forge`, …).
 */
loader?: string, sort: SearchSort, offset: number, };
