// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One search result, as shown in the browser.
 */
export type SearchHit = { projectId: string, projectType: string, slug: string, title: string, description: string, author: string, iconUrl: string | null, downloads: number, dateModified: string, categories: Array<string>, };
