// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MotdSpan } from "./MotdSpan";

export type ServerStatus = { 
/**
 * Server software / version text (`Paper 1.21.4`, `Velocity 3.x`).
 */
version: string, protocol: number, playersOnline: number, playersMax: number, 
/**
 * A few online player names, if the server shares them.
 */
playersSample: Array<string>, motd: Array<MotdSpan>, 
/**
 * `data:image/png;base64,…`
 */
icon: string | null, latencyMs: number, };
