// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Accent } from "./Accent";
import type { AuthSettings } from "./AuthSettings";
import type { Language } from "./Language";
import type { LaunchBehavior } from "./LaunchBehavior";

export type Settings = { schemaVersion: number, language: Language, accent: Accent, 
/**
 * Animated grid/particle background.
 */
backgroundEffects: boolean, 
/**
 * Verbose (debug-level) launcher logging.
 */
debugLogging: boolean, downloadConcurrency: number, defaultMemoryMb: number, launchBehavior: LaunchBehavior, auth: AuthSettings, };
