// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShaderSetup = { 
/**
 * Files downloaded into `mods/`.
 */
installed: Array<string>, 
/**
 * Projects skipped because a matching jar is already present.
 */
alreadyPresent: Array<string>, };
