// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemSource } from "./ItemSource";

export type SharedItem = { fileName: string, sha1: string, size: number, enabled: boolean, title: string | null, versionNumber: string | null, source: ItemSource, };
