// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SharedItem } from "./SharedItem";

export type SharedList = { id: number, owner: string, instanceId: string, instanceName: string, mcVersion: string, loader: string, items: Array<SharedItem>, updatedAt: string, };
