// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkinModel } from "./SkinModel";
import type { TextureKind } from "./TextureKind";
import type { Visibility } from "./Visibility";

export type SharedTexture = { 
/**
 * Server id of the share.
 */
id: number, kind: TextureKind, model: SkinModel, name: string, 
/**
 * Account name of the person who shared it.
 */
author: string, 
/**
 * SHA-1 of the PNG (= the library id of the same image).
 */
sha1: string, visibility: Visibility, 
/**
 * RFC 3339.
 */
createdAt: string, 
/**
 * Shared by this installation.
 */
mine: boolean, dataUri: string, };
