// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodePurpose } from "./CodePurpose";

export type SignUpResult = { "kind": "signedIn" } | { "kind": "codeSent", purpose: CodePurpose, };
