// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkinModel } from "./SkinModel";

export type SkinItem = { 
/**
 * `data:image/png;base64,…` (the webview may not read files).
 */
dataUri: string, 
/**
 * SHA-1 of the PNG.
 */
id: string, name: string, model: SkinModel, addedAt: number, };
