// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkinMcSkin } from "./SkinMcSkin";

export type SkinMcPage = { skins: Array<SkinMcSkin>, 
/**
 * Opaque token for the next page (the site's own link), if any.
 */
next?: string, };
