// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkinModel } from "./SkinModel";

export type SkinEntry = { 
/**
 * SHA-1 of the PNG.
 */
id: string, name: string, model: SkinModel, addedAt: number, };
