// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkinModel } from "./SkinModel";

export type SkinMcSkin = { 
/**
 * SkinMC skin id (UUID).
 */
id: string, 
/**
 * Account name of the creator ("" when the page shows none).
 */
author: string, model: SkinModel, 
/**
 * The skin PNG as a data URI (verified).
 */
dataUri: string, };
