// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorPayload } from "./ErrorPayload";
import type { Stage } from "./Stage";
import type { TaskKind } from "./TaskKind";
import type { TaskStatus } from "./TaskStatus";

export type TaskInfo = { id: string, kind: TaskKind, instanceId: string | null, title: string, 
/**
 * Account name a game task plays with (several accounts may play one
 * instance at once).
 */
account: string | null, status: TaskStatus, stage: Stage | null, done: number, total: number, bytesDone: number, bytesTotal: number, error: ErrorPayload | null, startedAt: number, finishedAt: number | null, };
