// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Version summary for the UI.
 */
export type VersionSummary = { id: string, name: string, versionNumber: string, versionType: string, gameVersions: Array<string>, loaders: Array<string>, datePublished: string, };
